# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test function
#' @export
put_option_pricer_af <- function(s, k, r, y, t, sigma) {
    .Call('_arrayfire_put_option_pricer_af', PACKAGE = 'arrayfire', s, k, r, y, t, sigma)
}

#' Test function
#' @export
put_option_pricer_arma <- function(s, k, r, y, t, sigma) {
    .Call('_arrayfire_put_option_pricer_arma', PACKAGE = 'arrayfire', s, k, r, y, t, sigma)
}

